In [64]:
import numpy as np
import tensorflow as tf #used to build and train nueral network
from tensorflow import keras # it is a high level API used to build nueral network easily
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [65]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [66]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [67]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [68]:
X = df[['soil_moisture','temperature_c','sunlight_hours']]
y = df['needs_water']

# Normalization - it converts the value from 0 to 1
# Standardization - it finds the mean of the data , then does the std deviation
X_min = X.min()
X_max = X.max()
X_scaled = (X-X_min)/(X_max-X_min + 1e-8)

In [69]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [70]:
X_train,X_test,y_train,y_test = train_test_split(X_scaled,y,test_size=0.2,random_state=42,stratify=y)

In [71]:
model = keras.Sequential([
    layers.Input(shape = (X_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(6,activation='softmax')
])

In [72]:
model.compile(optimizer='sgd',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [73]:
history = model.fit(X_train.values,y_train.values,
                    validation_data = (X_test.values,y_test.values),
                    epochs=100,batch_size=4,verbose=1
                    )

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 154ms/step - accuracy: 0.4167 - loss: 1.6211 - val_accuracy: 0.2500 - val_loss: 1.7741
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.3229 - loss: 1.6294 - val_accuracy: 0.2500 - val_loss: 1.7581
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.2917 - loss: 1.6005 - val_accuracy: 0.2500 - val_loss: 1.7421
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4479 - loss: 1.5662 - val_accuracy: 0.2500 - val_loss: 1.7261
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.2292 - loss: 1.5758 - val_accuracy: 0.2500 - val_loss: 1.7102
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.3854 - loss: 1.5025 - val_accuracy: 0.2500 - val_loss: 1.6945
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.2917 - loss: 1.5268 - val_accuracy: 0.2500 - val_loss: 1.6792
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5208 - loss: 1.4790 - val_accuracy: 0.2500 - val_loss: 1.6640
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.4583 - loss: 1.4571 - val_accuracy: 0.2500 - val_loss: 1.6491
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.3958 - loss: 1.4602 - val_accuracy: 0.2500 - val_loss: 1.6343
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.3333 - loss: 1.4651 - val_accuracy: 0.2500 - val_loss: 1.6196
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.3646 - loss: 1.4177 - val_accuracy: 0.2500 - val_loss: 1.6050
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.4583 - loss: 1.3792 - val_accuracy: 0.2500 - val_loss: 1.5906
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5938 - loss: 1.3659 - val_accuracy: 0.2500 - val_loss: 1.5763
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5625 - loss: 1.3497 - val_accuracy: 0.2500 - val_loss: 1.5622
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5625 - loss: 1.3471 - val_accuracy: 0.2500 - val_loss: 1.5482
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5000 - loss: 1.3553 - val_accuracy: 0.2500 - val_loss: 1.5344
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.4688 - loss: 1.3162 - val_accuracy: 0.2500 - val_loss: 1.5210
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5000 - loss: 1.2957 - val_accuracy: 0.2500 - val_loss: 1.5077
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5938 - loss: 1.2904 - val_accuracy: 0.2500 - val_loss: 1.4945
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.4375 - loss: 1.2786 - val_accuracy: 0.2500 - val_loss: 1.4815
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.5000 - loss: 1.2525 - val_accuracy: 0.2500 - val_loss: 1.4685
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.5312 - loss: 1.2288 - val_accuracy: 0.2500 - val_loss: 1.4557
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.4375 - loss: 1.2354 - val_accuracy: 0.2500 - val_loss: 1.4430
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 1.2359 - val_accuracy: 0.2500 - val_loss: 1.4305
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6562 - loss: 1.1650 - val_accuracy: 0.2500 - val_loss: 1.4181
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 1.1870 - val_accuracy: 0.2500 - val_loss: 1.4059
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.4375 - loss: 1.1990 - val_accuracy: 0.2500 - val_loss: 1.3939
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 1.1560 - val_accuracy: 0.2500 - val_loss: 1.3821
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5625 - loss: 1.1227 - val_accuracy: 0.2500 - val_loss: 1.3704
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.4062 - loss: 1.1903 - val_accuracy: 0.2500 - val_loss: 1.3589
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6250 - loss: 1.1261 - val_accuracy: 0.2500 - val_loss: 1.3476
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.3438 - loss: 1.1568 - val_accuracy: 0.2500 - val_loss: 1.3365
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 1.0971 - val_accuracy: 0.2500 - val_loss: 1.3255
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5938 - loss: 1.0768 - val_accuracy: 0.2500 - val_loss: 1.3147
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 1.1013 - val_accuracy: 0.2500 - val_loss: 1.3043
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 1.0522 - val_accuracy: 0.2500 - val_loss: 1.2941
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5312 - loss: 1.0727 - val_accuracy: 0.2500 - val_loss: 1.2841
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.4375 - loss: 1.0767 - val_accuracy: 0.2500 - val_loss: 1.2743
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5312 - loss: 1.0421 - val_accuracy: 0.2500 - val_loss: 1.2647
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 1.0256 - val_accuracy: 0.2500 - val_loss: 1.2553
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6562 - loss: 1.0099 - val_accuracy: 0.2500 - val_loss: 1.2460
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 1.0304 - val_accuracy: 0.2500 - val_loss: 1.2369
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.9923 - val_accuracy: 0.2500 - val_loss: 1.2280
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.9955 - val_accuracy: 0.2500 - val_loss: 1.2193
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.9841 - val_accuracy: 0.2500 - val_loss: 1.2107
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4375 - loss: 1.0011 - val_accuracy: 0.2500 - val_loss: 1.2023
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.4375 - loss: 0.9840 - val_accuracy: 0.2500 - val_loss: 1.1941
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.9991 - val_accuracy: 0.2500 - val_loss: 1.1860
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6562 - loss: 0.9377 - val_accuracy: 0.2500 - val_loss: 1.1782
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4688 - loss: 0.9436 - val_accuracy: 0.2500 - val_loss: 1.1705
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4062 - loss: 0.9659 - val_accuracy: 0.2500 - val_loss: 1.1630
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4688 - loss: 0.9354 - val_accuracy: 0.2500 - val_loss: 1.1557
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.4375 - loss: 0.9695 - val_accuracy: 0.2500 - val_loss: 1.1485
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5938 - loss: 0.9256 - val_accuracy: 0.2500 - val_loss: 1.1414
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.9114 - val_accuracy: 0.2500 - val_loss: 1.1345
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.4062 - loss: 0.9271 - val_accuracy: 0.2500 - val_loss: 1.1276
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.4688 - loss: 0.9060 - val_accuracy: 0.2500 - val_loss: 1.1209
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5625 - loss: 0.9089 - val_accuracy: 0.2500 - val_loss: 1.1143
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.3750 - loss: 0.9306 - val_accuracy: 0.2500 - val_loss: 1.1079
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5625 - loss: 0.8728 - val_accuracy: 0.2500 - val_loss: 1.1016
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.9156 - val_accuracy: 0.5000 - val_loss: 1.0954
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5729 - loss: 0.8891 - val_accuracy: 0.5000 - val_loss: 1.0894
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5729 - loss: 0.8894 - val_accuracy: 0.5000 - val_loss: 1.0835
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5312 - loss: 0.8934 - val_accuracy: 0.5000 - val_loss: 1.0777
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5417 - loss: 0.8784 - val_accuracy: 0.5000 - val_loss: 1.0720
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6354 - loss: 0.8615 - val_accuracy: 0.5000 - val_loss: 1.0664
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5729 - loss: 0.8608 - val_accuracy: 0.5000 - val_loss: 1.0610
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5729 - loss: 0.8764 - val_accuracy: 0.5000 - val_loss: 1.0556
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7083 - loss: 0.8547 - val_accuracy: 0.5000 - val_loss: 1.0503
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6042 - loss: 0.8445 - val_accuracy: 0.5000 - val_loss: 1.0452
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5729 - loss: 0.8480 - val_accuracy: 0.5000 - val_loss: 1.0401
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6354 - loss: 0.8191 - val_accuracy: 0.5000 - val_loss: 1.0351
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6771 - loss: 0.8145 - val_accuracy: 0.5000 - val_loss: 1.0302
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6042 - loss: 0.8144 - val_accuracy: 0.2500 - val_loss: 1.0255
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6771 - loss: 0.8108 - val_accuracy: 0.2500 - val_loss: 1.0208
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7083 - loss: 0.8134 - val_accuracy: 0.2500 - val_loss: 1.0163
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.6979 - loss: 0.8114 - val_accuracy: 0.2500 - val_loss: 1.0119
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7083 - loss: 0.7930 - val_accuracy: 0.2500 - val_loss: 1.0076
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7083 - loss: 0.8161 - val_accuracy: 0.2500 - val_loss: 1.0034
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7083 - loss: 0.7981 - val_accuracy: 0.2500 - val_loss: 0.9993
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6771 - loss: 0.7900 - val_accuracy: 0.2500 - val_loss: 0.9953
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.7396 - loss: 0.8129 - val_accuracy: 0.2500 - val_loss: 0.9913
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6771 - loss: 0.7975 - val_accuracy: 0.2500 - val_loss: 0.9875
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6042 - loss: 0.8096 - val_accuracy: 0.2500 - val_loss: 0.9837
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.4792 - loss: 0.8099 - val_accuracy: 0.2500 - val_loss: 0.9801
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6146 - loss: 0.8105 - val_accuracy: 0.2500 - val_loss: 0.9765
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5729 - loss: 0.7895 - val_accuracy: 0.2500 - val_loss: 0.9729
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5104 - loss: 0.7887 - val_accuracy: 0.2500 - val_loss: 0.9694
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5417 - loss: 0.7870 - val_accuracy: 0.2500 - val_loss: 0.9659
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5729 - loss: 0.7864 - val_accuracy: 0.2500 - val_loss: 0.9625
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5417 - loss: 0.7813 - val_accuracy: 0.2500 - val_loss: 0.9592
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.4479 - loss: 0.7985 - val_accuracy: 0.2500 - val_loss: 0.9560
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6042 - loss: 0.7777 - val_accuracy: 0.2500 - val_loss: 0.9529
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6354 - loss: 0.7544 - val_accuracy: 0.2500 - val_loss: 0.9498
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6146 - loss: 0.7782 - val_accuracy: 0.2500 - val_loss: 0.9467
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7396 - loss: 0.7671 - val_accuracy: 0.2500 - val_loss: 0.9435
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6458 - loss: 0.7830 - val_accuracy: 0.2500 - val_loss: 0.9404
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.8021 - loss: 0.7469 - val_accuracy: 0.2500 - val_loss: 0.9373
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.7083 - loss: 0.7507 - val_accuracy: 0.2500 - val_loss: 0.9343

In [74]:
from tensorflow.keras import optimizers
opt = optimizers.SGD(learning_rate=0.01,momentum=0.9)